# Generated by Django 5.2.6 on 2025-09-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('womac_pain_walking', models.IntegerField()),
                ('womac_pain_stairs', models.IntegerField()),
                ('womac_pain_nocturnal', models.IntegerField()),
                ('womac_pain_rest', models.IntegerField()),
                ('womac_pain_weight_bearing', models.IntegerField()),
                ('womac_stiffness_morning', models.IntegerField()),
                ('womac_stiffness_later_day', models.IntegerField()),
                ('womac_function_descend_stairs', models.IntegerField()),
                ('womac_function_ascend_stairs', models.IntegerField()),
                ('womac_function_rising_sitting', models.IntegerField()),
                ('womac_function_standing', models.IntegerField()),
                ('womac_function_bending_floor', models.IntegerField()),
                ('womac_function_walking_flat', models.IntegerField()),
                ('womac_function_in_out_car', models.IntegerField()),
                ('womac_function_shopping', models.IntegerField()),
                ('womac_function_putting_socks', models.IntegerField()),
                ('womac_function_lying_bed', models.IntegerField()),
                ('womac_function_taking_socks_off', models.IntegerField()),
                ('womac_function_rising_bed', models.IntegerField()),
                ('womac_function_in_out_bath', models.IntegerField()),
                ('womac_function_sitting', models.IntegerField()),
                ('womac_function_on_off_toilet', models.IntegerField()),
                ('womac_function_heavy_domestic', models.IntegerField()),
                ('womac_function_light_domestic', models.IntegerField()),
                ('vas_pain', models.IntegerField()),
                ('satisfaction', models.IntegerField()),
                ('ambulation', models.CharField(choices=[('independent', 'Independent'), ('cane', 'Uses Cane'), ('walker', 'Uses Walker'), ('wheelchair', 'Wheelchair-bound')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
